spring:
  profiles:
    active: dev

#三方短信
sms:
  host: http://yzxtz.market.alicloudapi.com/yzx/notifySms
  appcode: 84892d9b92974a88a2a40aed0dcf0773

#阿里云短信
alisms:
  appId: LTAIbNPovuHJy8ak
  appkey: ULaRPWWZjUy92oJ1AEjgHe90taoPxG

#腾讯云短信
tencentsms:
  appId: 1400203480 #短信应用SDK AppID,1400开头
  appkey: 886d290a3fa557ff255afe582cc73311 #短信应用SDK AppKey
  templateId: 7839 #短信模板ID，需要在短信应用中申请, NOTE: 这里的模板ID`7839`只是一个示例，真实的模板ID需要在短信控制台中申请
  smsSign: 鸟巢咖啡 #签名,这里的签名"腾讯云"只是一个示例，真实的签名需要在短信控制台中申请，另外签名参数使用的是`签名内容`，而不是`签名ID`
#微信
wecat:
  appId: wx4efe77aac1e735c6
  appSecret: 5c5de6885810fc002a351c8654809ed6
  token: cloudtop
  backUrl: http://u547cb.natappfree.cc/nckf-boot/api/user/callBack

#微博
weibo:
  appId: 1768380590
  appSecret: 33bf157d02042a50e080101e003d037e
  backUrl: http://u547cb.natappfree.cc/nckf-boot/api/user/wb_callback

#邮箱
mail:
  username: sanshixuxian@163.com
  password: a75861943

#本地ip
local :
  ip : http://192.168.1.119