server:
  port: 8081
  servlet:
    context-path: /nckf-boot
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
management:
 endpoints:
  web:
   exposure:
    include: metrics,httptrace
    
spring:
#  mail:
#    host: smtp.163.com
#    username: sanshixuxian@163.com
#    password: a75861943
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
  ## quartz定时任务,采用数据库方式
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
  quartz:
    job-store-type: jdbc
  #json 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
  aop:
    proxy-target-class: true
  #配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/,classpath:/h5/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          url: jdbc:mysql://39.105.129.64:3306/nckf-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false
          username: root
          password: 1234qwer
          driver-class-name: com.mysql.jdbc.Driver
          # 多数据源配置
          #multi-datasource1:
          #url: jdbc:mysql://localhost:3306/nckf-boot2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
          #username: root
          #password: root
          #driver-class-name: com.mysql.jdbc.Driver
  #redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: ''
    port: 6379
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:org/benben/modules/**/xml/*Mapper.xml

#benben专用配置
benben :
  path :
    #文件上传根目录 设置
    upload: D://upFiles
    #webapp文件路径
    webapp: D://webapp

ali:
  pay:
    APPID: 2016091500517208
    #支付宝私钥
    RSA_PRIVATE_KEY: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCI+MxFTO8Q8iZ3cKqQl7CHiJ2vcND5q2drRzgJQ1MJiqako7ZqqTMpXKj2GY3eRLrTVyjYIDJRrgbDQEI8X4yml5Q1JRJ4fkAHLFhQhTEUJftmy7I8BmmoihOnCWoXmrFEN/lKm3cQ9/wEHYKjTOSktIQb35IGDzsrB+KOUMGg5Q9bdhwrkKMHc7V2jnVH+V7IB3YJGQ4qoQUSuKjWH/d0BFwArfllOftp7ZZT24MejELAN1Eu4Pjd7bIpAnhY9oLGrRKRF35fFslKITm9xLXOHy4gSw9sozYLaD6CSr+vHupofceut1F64ctw6jhIUrRfh/aPrnsvaawazHpaAUvdAgMBAAECggEBAIbkb1e4gqAvug5a2L95hBKWSqTi+AtJ8JnIE7mbogV9lMwDpry4UXhklsl3NS42hb9o0QK4ApZKSsKzYAfRGdVe5kjIb75Wp3vpAjiaU1FCbqo35RoUPq4K/Xu9W8xPPlCux0XggYwmjP0IiwWDzpEebhR9Q3PQQDcKluYNRgPK10SEvwEV0rHDTjAPZ3LhdDNdwnQaVZquf42FAi/EHzYdmT7a2stohj9WH/SxX95pRVV1IMap5Z6Pwr3uwrtUvl1BVyJSYdEdLhQ8M8U19hBWZKlml8xepTByVwsvTPOXHGTvuGHx7OLwjrrBhJkXtqcXg9bpUS7iKBrLNrL4uEkCgYEA7Gt9/GZE7kPKOydD4Tx5Imb2kPBcScv4nCbbPAg2hPB64BdGEWX9H1WET6ZoiY+5FxNcTOybTsu8BoeBe7c9ixcWfrsSPa3KB8J2IzKqGFxaU/t4dgBdQOsaBL+Rbmo2tu4rJ1HGbEDpOKd2UmBO1Zbeu/kkQQL9U94KcSOZLKsCgYEAlFDWOqPKym4zptzq5QOaq/FtdrQ9xZBG+Fi9m46rlVR7+hrwIUdjsTQR09a78lT7cEiE9+qOaDwbBmY/Z1Hhe0yemJTIbmVCgo26Vb0Q4FtHEL0CQUL/PwIVWW4qpzGlWe2R/xkdOohVZYhtKmll7cgW10Jwhke7CMlQeMVh2ZcCgYBNH4e6xZXo7/5Rq65uFG8jtNjsUSyZ+ksAjYBpJfi7B0PeRFlcJZwcE6aU4SEq9tKXX351rZ3AZ5/PtXac6BrQe9ifwODjdAT64Qnu04E/bykcSmVygQ3qtocHU4LatRViOXGkYv3KpKYwEBj+KGKvNIc2ZMDZ4GLJcB6R5934/wKBgDV+qqZf6Yb2FJ8802Ri1mjqHYdRH26gyVhN+aWf4fdsj4L4MGBwdV623y8/Jm8Tg9VN8tfQvCiQdVbrjjbf66ojSpjSITDgSQr5v5mpJesmQQ2ifqu3VIUPZU/qUmwXlgJHk/8kucwg3FxQxr8jYOZQ4xwlFJz6RlW29tV4rABlAoGAPS16kH9zX9dBf8q0wnTZRQCiVID8lqE7kGe5l9v/JiZ+7kezf6EVOFXxq05uTB9r8aqCM4OA8v8OyvBuSW91Itebx9mA+8XuyVPophEIDlTuOadFrEFo+M4Vd59CjE7N9pQu7+cLHsYhTH/Q/qiREles3r2sIDnpDphedBMwb0w=
    #支付宝公钥
    ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvT6rWjBTJVcCZ9CgmJahL5uHVU6392cJQTxEYaYc01F5kZRDuYME20XuXE7M3pRQ0ZDRiA+GYVUHvw0E75J6mTh3XXEF5dNSsNMFl7IWoF6NGPGgbap9uHH7/vj/YvW6OIGnbHGxWmQO0G7tTkyOeUl8uci3D/5vUZGvs2yRUHpKVTLjBwXUnsWeEZ6HrGUSy4Ss4l67gKM4FGnAaeBQkguqjnkuidfV48XxYo5pd6lHAVteMvOzsa6IrwbPqGVKsQEE6MEJALlBUdJjNDLUO6OWpd+2a8MqmHU1CdccnWruUenTKI2GToUAfiOaKm0xY8pvX1SMobdTjkVffvv5HQIDAQAB
    notify_url: http://nckf.aipython.top/nckf-boot/benben_pay/notify_url
    return_url:
    URL: https://openapi.alipaydev.com/gateway.do
    CHARSET: UTF-8
    FORMAT: json
    SIGNTYPE: RSA2


wx:
  pay:
    mchId: 1496550442
    mchKey: SI947oGb40SrJ3iZOLlj5AATmx459MDp
    appId: WX76b20ld66fca06ed
    notify_url: http://nckf.aipython.top/nckf-boot/wxpay/wxnotify


